// Puerto de `www/src/Helpers/TransferBankHelper.php::countryFlags()`.
export const TRANSFER_BANK_COUNTRIES: Record<string, string> = {
  Colombia: "🇨🇴",
  México: "🇲🇽",
  Argentina: "🇦🇷",
  Chile: "🇨🇱",
  Perú: "🇵🇪",
  Venezuela: "🇻🇪",
  Ecuador: "🇪🇨",
  Brasil: "🇧🇷",
  Panamá: "🇵🇦",
  Belice: "🇧🇿",
  "Costa Rica": "🇨🇷",
  "República Dominicana": "🇩🇴",
  Uruguay: "🇺🇾",
  Bolivia: "🇧🇴",
  Paraguay: "🇵🇾",
  Guatemala: "🇬🇹",
  Honduras: "🇭🇳",
  "El Salvador": "🇸🇻",
  Nicaragua: "🇳🇮",
  España: "🇪🇸",
  "Reino Unido": "🇬🇧",
  Otro: "🌐",
};
